tasks:
  - name: backend
    command: |
      cd backend
      ./mvnw spring-boot:run
    openMode: tab
    port: 8080

  - name: frontend
    command: |
      cd frontend
      dotnet run --urls=http://localhost:5000
    openMode: tab
    port: 5000

ports:
  - port: 8080
    onOpen: ignore
  - port: 5000
    onOpen: open-preview
